### PR TITLE
Add meteor as user of glamour

### PR DESCRIPTION
**Pull request by ravisuhag**

### CODE REVIEW

**Comment by muesli** [comment]
@ravisuhag Happy to add projects, but I don't actually see meteor using glamour?

**Comment by ravisuhag** [comment]
> @ravisuhag Happy to add projects, but I don't actually see meteor using glamour?

@muesli `meteor` [info](https://github.com/odpf/meteor/blob/main/cmd/info.go) command uses Glamour to print info of a plugin. 

For reusability, we have extracted it in the [salt](https://github.com/odpf/salt/blob/main/printer/markdown.go) package but the meteor is still the end-user of it.

**Comment by muesli** [comment]
@ravisuhag Thank you, will merge!

**Comment by ravisuhag** [comment]
@muesli Glamour and the entire charm ecosystem tools are amazing by the way. Absolute fan! Thanks for these amazing tools.

**Pull request merged**
