### PR TITLE
Optionally Preserving New Lines

### PR DESCRIPTION
**Pull request by wilso199**
#70 Allowing for new lines to be preserved in paragraph elements.

I wasn't sure where to place the tests for this functionality. If you could provide some direction, I am happy to add them.

### CODE REVIEW

**Comment by muesli** [comment]
Fantastic, thank you! I wonder if `WithNewLines` is the best name tho. Maybe `WithPreservedNewLines` is a bit more accurate & self-explanatory?

**Comment by wilso199** [comment]
@muesli I agree with you - `WithPreservedNewLines` is more understandable. I have modified the name of the function and the render options boolean to match. Thanks for the feedback!

**Comment by muesli** [comment]
Thank you, that looks good to me! Would you mind also adding a test for this new functionality?

**Comment by wilso199** [comment]
Added a test case here for the preserve new line functionality. Happy to adjust based on any feedback you have.

**Comment by muesli** [comment]
That looks just fine! The testdata is a bit all over the place as we use the style examples as additional test input. Even though I think that makes sense, it probably just confuses people a bit. Thank you for your contribution :heart:

**Pull request merged**
