### PR TITLE
Implement Capitalization

### LINKED ISSUE #100: Add style to capitalize/lowercase text
It would be awesome to be able to apply text transformations that manipulate capitalization, e.g.:

```json
"heading": {
  "bold": true
},
"h1": {
  "upper": true,
},
"h3": {
  "lower": true
}
```

converts:

```md
# This is a header
### This is a subheader
```

into:

# THIS IS A HEADER
### this is a subheader

### PR DESCRIPTION
**Pull request by lepasq**
Fixes #100 (adds lower and upper case styling).

I used an example, in which `h1` and `h3` tags were wrongly capitalized. This produced the following output:
arrows

You can rerun the example, by running `go run examples/capitalization/main.go` and by making `h1` upper case and `h3` lower case by adding the following lines to `styles.go`:

### CODE REVIEW

**Comment by lepasq** [comment]
I realized that `upper` should make *all* letters upper case, not just the initial one.  
This is what the previous message looks like now, using the same code as before  
image

**Comment by muesli** [comment]
This looks nice, thank you! I imagine an option for using [title case](https://en.wikipedia.org/wiki/Title_case) would also be appreciated. Could you also try and add a test-case for these styling options?

**Comment by lepasq** [comment]
Sure, I'm going to work on that!

**Comment by lepasq** [comment]
I got rid of the example file, since there now is a unit test for the capitalization options.  
I wasn't sure if there is a way to assign a value to a nil-pointer without creating a new variable.  
Therefore, I used the following workaround:  

```go
var s bool = true
var p *bool = &s

style := DarkStyleConfig
style.H1.Upper = p
style.H2.Title = p
style.H3.Lower = p
```

Is there a cleaner way to do this?

**Comment by muesli** [comment]
> Is there a cleaner way to do this?

Only slightly, but still nicer to read:

```go
b := true
style.H1.Upper = &b
```

**Comment by lepasq** [comment]
Thanks! I updated that section in the code.

**Comment by muesli** [comment]
Thank you for your contribution! :heart:

**Comment by lepasq** [comment]
You're welcome!

**Pull request merged**
